# Assignment-5

This notebook contains the questions to test the proficiency in `Mathematics and Probability`.

### Date: 26th September, 2026

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the coding questions in the notebook and save it.
- Rename the file as `Assignment-05-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-05-Dipika_Chopra.ipynb`.
- For numerical problems you can either solve the same using `LaTeX` in markdown cell of your soluton notebook or you can solve it on paper and upload the scan pdf copy of the solution.
- If you are solving it on paper then name the pdf file of the scan copy of the solution as `Assignment-05-<your_name>_<your_surname>.pdf`. For example if your name is Akash Kumar then name the file as `Assignment-05-Akash_Kumar.pdf`.
- Upload the solved notebook in your github repo under the folder **Assignment-5**.
- Upload the solved notebook and the scanned pdf copy of the solutions in the google drive location:https://drive.google.com/drive/folders/1VfPbQVM5kOrzFGXoyuETp8LiNJdj-GKa?usp=drive_link
<h3><span style="color:red"> Deadline: 11th October, 2026 </span></h3>

<h5><span style="color:blue"> <b>Instructions:</b> Please answer all the questions. For problems requiring numerical solutions, you are encouraged to write code in Python to compute the results. Show your steps and explain your reasoning. </span></h5>

### Problem-1

In a network, data packets are sent through a shared channel. Suppose there are 10 devices attempting to send data. In any given time slot, each device has a 20% chance of attempting to send a packet, independently of other devices. A collision occurs if two or more devices attempt to send a packet in the same time slot. What is the probability that in a given time slot, there will be no collisions?

Problem 1 — Probability of No Collision

There are 10 devices, and each device independently attempts to send with probability:

$$ p=0.20 $$

Therefore, the probability that a device does not attempt is:

$$ q=1-0.20=0.80 $$

A collision occurs when 2 or more devices attempt simultaneously.

So, no collision means either:

No device attempts, or
Exactly one device attempts.
Case 1: No device attempts
$$ P(0)=\binom{10}{0}(0.2)^0(0.8)^{10} $$ $$ P(0)=0.8^{10}=0.1073741824 $$
Case 2: Exactly one device attempts
$$ P(1)=\binom{10}{1}(0.2)^1(0.8)^9 $$ $$ P(1)=10(0.2)(0.8)^9 $$ $$ P(1)=0.268435456 $$

Therefore:

$$ P(\text{no collision})=P(0)+P(1) $$ $$ =0.1073741824+0.268435456 $$ $$ \boxed{P(\text{no collision})=0.3758096384} $$

So the probability is approximately:

37.58%
	​


In [1]:
import math

n = 10
p = 0.20
q = 1 - p

prob_no_collision = (q ** n) + (n * p * q ** (n - 1))

print(prob_no_collision)
print(prob_no_collision * 100)

0.3758096384000002
37.58096384000002


### Problem-2

A system uses 8-character passwords. Each character can be any lowercase letter (a-z), uppercase letter (A-Z), or digit (0-9).
What is the probability that a randomly generated 8-character password contains at least one digit, given that character repetition is allowed?

The password has 8 characters.

Each character can be:

26 lowercase letters
26 uppercase letters
10 digits

Total possible characters:

$$ 26+26+10=62 $$

We need:

$$ P(\text{at least one digit}) $$

It is easier to calculate the complement:

$$ P(\text{at least one digit}) =1-P(\text{no digits}) $$
Probability that one character is not a digit

There are 52 letters out of 62 possible characters:

$$ P(\text{not digit})=\frac{52}{62}=\frac{26}{31} $$

For all 8 characters to contain no digit:

$$ P(\text{no digit})=\left(\frac{52}{62}\right)^8 $$

Therefore:

$$ P(\text{at least one digit}) = 1-\left(\frac{52}{62}\right)^8 $$ $$ =1-\left(\frac{26}{31}\right)^8 $$

Approximately:

$$ \boxed{0.7442} $$

or

74.42%
	​


In [2]:
prob_at_least_one_digit = 1 - (52 / 62) ** 8

print(prob_at_least_one_digit)
print(prob_at_least_one_digit * 100)

0.7551538761591853
75.51538761591853


### Problem-3

A software project has two modules, A and B. The probability that module A has a bug is 0.15, and the probability that module B has a bug is 0.10. The probability that both modules have bugs is 0.03.

(a) What is the probability that module A has a bug, given that module B has a bug?

(b) What is the probability that module B has a bug, given that module A does not have a bug?

Conditional Probability

Given:

$$ P(A)=0.15 $$ $$ P(B)=0.10 $$ $$ P(A\cap B)=0.03 $$

The conditional probability formula is:

$$ P(A|B)=\frac{P(A\cap B)}{P(B)} $$
(a) Probability that A has a bug given that B has a bug

We need:

$$ P(A|B) $$

Using the formula:

$$ P(A|B)=\frac{P(A\cap B)}{P(B)} $$

Substitute the values:

$$ P(A|B)=\frac{0.03}{0.10} $$ $$ \boxed{P(A|B)=0.30} $$

Therefore:

$$ \boxed{P(A|B)=30\%} $$
(b) Probability that B has a bug given that A does not have a bug

We need:

$$ P(B|A^c) $$

where \(A^c\) means A does not have a bug.

First calculate:

$$ P(A^c)=1-P(A) $$ $$ P(A^c)=1-0.15=0.85 $$

Now we need:

$$ P(B\cap A^c) $$

Since B can occur either with A or without A:

$$ P(B)=P(A\cap B)+P(A^c\cap B) $$

Therefore:

$$ P(A^c\cap B)=P(B)-P(A\cap B) $$ $$ =0.10-0.03 $$ $$ =0.07 $$

Now apply conditional probability:

$$ P(B|A^c)=\frac{P(B\cap A^c)}{P(A^c)} $$ $$ =\frac{0.07}{0.85} $$ $$ \boxed{P(B|A^c)\approx0.08235} $$

Therefore:

P(B∣A
c
)≈8.24%
	​


### Problem-4

A robot uses a sensor to detect an obstacle. The sensor has a 95% chance of correctly detecting an obstacle when one is present (true positive rate). However, it also has a 2% chance of indicating an obstacle when there isn't one (false positive rate).
In the robot's environment, obstacles are present 10% of the time.

What is the probability that an obstacle is truly present, given that the sensor indicates an obstacle?

Problem 4 — Bayes' Theorem

We know:

P(O)=0.10: obstacle is present
P(Sensor+ |O)=0.95: sensor detects it when present
P(Sensor+ |O^c)=0.02: false positive rate

We want:

P(O|Sensor+)

Bayes' theorem gives:

P(O |Sensor) = P(Sensor+|O)P(O)/ P(Sensor+)

The denominator can be calculated using the law of total probability:

P(Sensor+) = P(Sensor+ | O)P(O) + P(Sensor+ | O^c)P(O^c)

First, calculate:

P(O^c)=1-0.10

What is \(P(O^c)\)?
Bayes' Theorem

Given:

P(O)=0.10
P(O^c)=1-0.10=0.90
P(S+|O)=0.95
P(S+|O^c)=0.02

We want:

P(O|S+)

where S+ means the sensor indicates an obstacle.

Step 1: Calculate the probability of a positive sensor reading

Using the law of total probability:

P(S+)=P(S+|O)P(O)+P(S+|O^c)P(O^c)

Substitute:

P(S+)=(0.95)(0.10)+(0.02)(0.90)
=0.095+0.018 
=0.113
Step 2: Apply Bayes' theorem
P(O|S+)=P(S+|O)P(O)/{P(S+)}
(0.95)(0.10)/{0.113}
0.095/0.113 
P(O|S+)\approx 0.8407

Therefore:

P(O∣S+)≈84.07%
	​


### Problem-5

A spam filter uses a keyword "money" to identify spam emails.
- 10% of all emails are spam.
- If an email is spam, the word "money" appears in it 80% of the time.
- If an email is not spam, the word "money" appears in it 5% of the time.

If an email contains the word "money", what is the probability that it is spam?

Given:

P(S)=0.10 — probability an email is spam
P(S^c)=0.90 — probability it is not spam
P(M|S)=0.80 — "money" appears in spam
P(M|S^c)=0.05 — "money" appears in non-spam

We want:

P(S|M)

Again, use Bayes' theorem:

P(S|M)=P(M|S)P(S)/P(M)
Step 1: Calculate \(P(M)\)
P(M)=P(M|S)P(S)+P(M|S^c)P(S^c)
=(0.80)(0.10)+(0.05)(0.90)
=0.08+0.045
=0.125
Step 2: Apply Bayes' theorem
P(S|M)=(0.80)(0.10)/{0.125
=0.08/0.125
=0.64

Therefore:

P(S|M)=64

Answer: 64%

Key idea

Even though "money" appears in 80% of spam emails, seeing the word "money" does not mean there's an 80% chance the email is spam. We must also account for how frequently the word occurs in legitimate emails and the overall spam rate.

### Problem-6

A rare disease affects 1 in 10,000 people. A diagnostic test for this disease has a 99% true positive rate (correctly identifies the disease when present) and a 0.5% false positive rate (incorrectly indicates the disease when not present).

If a randomly selected person tests positive for the disease, what is the probability that they actually have the disease?

Rare Disease

Given:

Disease prevalence:
$$ P(D)=\frac{1}{10000}=0.0001 $$
Therefore:
$$ P(D^c)=0.9999 $$
True positive rate:
$$ P(+|D)=0.99 $$
False positive rate:
$$ P(+|D^c)=0.005 $$

We want:

$$ P(D|+) $$
Step 1: Calculate probability of a positive test
$$ P(+)=P(+|D)P(D)+P(+|D^c)P(D^c) $$

Substitute:

$$ P(+) =(0.99)(0.0001)+(0.005)(0.9999) $$ $$ =0.000099+0.0049995 $$ $$ =0.0050985 $$
Step 2: Apply Bayes' theorem
$$ P(D|+)=\frac{P(+|D)P(D)}{P(+)} $$ $$ =\frac{0.99(0.0001)}{0.0050985} $$ $$ =\frac{0.000099}{0.0050985} $$ $$ \approx0.01942 $$

Therefore:

$$ \boxed{P(D|+)\approx1.94\%} $$

Answer: approximately 1.94%

This is an important example of the base-rate effect: because the disease is extremely rare, false positives among the much larger healthy population can substantially outnumber true positives.

### Problem-7

A batch of 500 microchips is produced. The probability that a single microchip is defective is 0.02.
Let X be the number of defective microchips in a random sample of 20 microchips from this batch. Assume the sample is taken with replacement, or the batch is large enough that we can model this as independent trials.

(a) What is the probability that exactly 3 microchips in the sample are defective?
(b) What is the probability that at least 2 microchips in the sample are defective?

Binomial Distribution

We have:

Number of trials:
$$ n=20 $$
Probability of a defective chip:
$$ p=0.02 $$
Probability of a non-defective chip:
$$ q=1-p=0.98 $$

Since each trial has two possible outcomes—defective or not defective—we use the binomial distribution.

The formula is:

$$ P(X=k)=\binom nk p^k(1-p)^{n-k} $$
(a) Exactly 3 defective chips

Here:

$$ k=3 $$

Therefore:

$$ P(X=3)=\binom{20}{3}(0.02)^3(0.98)^{17} $$

Calculate:

$$ \binom{20}{3} =\frac{20!}{3!17!} =1140 $$

Thus:

$$ P(X=3)=1140(0.02)^3(0.98)^{17} $$

Using Python or a calculator:

$$ \boxed{P(X=3)\approx0.00707} $$

or approximately:

0.707%
	​


In [3]:
import math

n = 20
p = 0.02
k = 3

prob_3 = math.comb(n, k) * (p ** k) * ((1-p) ** (n-k))

print(prob_3)
print(prob_3 * 100)

0.006469014507567489
0.6469014507567489


(b) At least 2 defective chips

"At least 2" means:

$$ X\ge2 $$

We could calculate:

$$ P(X=2)+P(X=3)+\cdots+P(X=20) $$

But that's tedious.

Instead, use the complement:

$$ P(X\ge2)=1-P(X<2) $$

Since \(X<2\) means \(X=0\) or \(X=1\):

$$ P(X\ge2)=1-[P(X=0)+P(X=1)] $$
Calculate \(P(X=0)\)
$$ P(X=0)=\binom{20}{0}(0.02)^0(0.98)^{20} $$ $$ \approx0.66761 $$
Calculate \(P(X=1)\)
$$ P(X=1)=\binom{20}{1}(0.02)^1(0.98)^{19} $$ $$ \approx0.27248 $$

Therefore:

$$ P(X\ge2)=1-(0.66761+0.27248) $$ $$ \boxed{P(X\ge2)\approx0.05991} $$

or approximately:

5.99%
	​


In [4]:
import math

n = 20
p = 0.02

p0 = math.comb(n, 0) * (p ** 0) * ((1-p) ** n)
p1 = math.comb(n, 1) * (p ** 1) * ((1-p) ** (n-1))

prob_at_least_2 = 1 - (p0 + p1)

print(prob_at_least_2)
print(prob_at_least_2 * 100)

0.05989897854894899
5.989897854894899


### Problem-8

The time (in hours) until a critical server component fails follows an exponential distribution with a mean of 500 hours.

(a) What is the probability that the component will last between 400 and 600 hours?

(b) The component has already been running for 300 hours without failure. What is the probability that it will last for at least another 250 hours?

Exponential Distribution

The mean lifetime is:

$$ 500\text{ hours} $$

For an exponential distribution:

$$ \lambda=\frac{1}{\text{mean}} $$

Therefore:

$$ \lambda=\frac{1}{500}=0.002 $$

The survival function is:

$$ P(X>t)=e^{-\lambda t} $$
(a) Probability the component lasts between 400 and 600 hours

We want:

$$ P(400<X<600) $$

This can be calculated as:

$$ P(X<600)-P(X<400) $$

For an exponential distribution:

$$ P(X<t)=1-e^{-\lambda t} $$

Therefore:

$$ P(400<X<600) = e^{-\lambda(400)}-e^{-\lambda(600)} $$

Substitute \(\lambda=0.002\):

$$ =e^{-0.8}-e^{-1.2} $$ $$ \approx0.44933-0.3010 $$ $$ \boxed{P(400<X<600)\approx0.1483} $$

Therefore:

14.83%
	​


In [5]:
import math

lam = 1 / 500

prob_400_600 = math.exp(-lam * 400) - math.exp(-lam * 600)

print(prob_400_600)
print(prob_400_600 * 100)

0.14813475220501943
14.813475220501942


(b) Already running for 300 hours

We want the probability that it lasts at least another 250 hours, given that it has already survived 300 hours:

$$ P(X>550\mid X>300) $$

The exponential distribution has the memoryless property:

$$ P(X>s+t|X>s)=P(X>t) $$

Therefore:

$$ P(X>550|X>300)=P(X>250) $$

Now:

$$ P(X>250)=e^{-\lambda(250)} $$ $$ =e^{-0.002(250)} $$ $$ =e^{-0.5} $$ $$ \boxed{\approx0.60653} $$

Therefore:

$$ \boxed{60.65\%} $$

The important concept is that for an exponential distribution, the previous 300 hours do not change the probability of surviving another 250 hours.

### Problem-9

The noise in a sensor's reading can be modeled by a Gaussian (Normal) distribution with a mean of 0 (bias) and a standard deviation of 0.5 units.

(a) What is the probability that a sensor reading's noise is between -0.2 and 0.3 units?

(b) If a reading is considered an "outlier" if its noise is more than 1.5 standard deviations away from the mean, what is the probability that a random reading is an outlier?

Normal Distribution

Given:

$$ X\sim N(\mu=0,\sigma=0.5) $$

We convert \(X\) to a standard normal variable using:

$$ Z=\frac{X-\mu}{\sigma} $$

where:

$$ \mu=0,\qquad \sigma=0.5 $$
(a) Noise between -0.2 and 0.3

We want:

$$ P(-0.2<X<0.3) $$
Convert -0.2 to a Z-score
$$ Z_1=\frac{-0.2-0}{0.5} $$ $$ Z_1=-0.4 $$
Convert 0.3 to a Z-score
$$ Z_2=\frac{0.3-0}{0.5} $$ $$ Z_2=0.6 $$

Therefore:

$$ P(-0.2<X<0.3) = P(-0.4<Z<0.6) $$

Using the standard normal CDF:

$$ \Phi(0.6)\approx0.72575 $$

and

$$ \Phi(-0.4)\approx0.34458 $$

Therefore:

$$ P(-0.4<Z<0.6) =0.72575-0.34458 $$ $$ \boxed{\approx0.38117} $$

Therefore:

38.12%
	​


In [8]:
!pip install scipy

In [9]:
from scipy.stats import norm

mu = 0
sigma = 0.5

prob = norm.cdf(0.3, mu, sigma) - norm.cdf(-0.2, mu, sigma)

print(prob)
print(prob * 100)

0.38116862386025063
38.11686238602506


(b) Probability of being an outlier

An outlier is defined as being more than 1.5 standard deviations away from the mean.

So:

$$ |Z|>1.5 $$

Because the normal distribution is symmetric:

$$ P(|Z|>1.5) = 2P(Z>1.5) $$

From the standard normal distribution:

$$ \Phi(1.5)\approx0.93319 $$

Therefore:

$$ P(Z>1.5)=1-0.93319 $$ $$ =0.06681 $$

Multiply by 2:

$$ P(|Z|>1.5)=2(0.06681) $$ $$ \boxed{\approx0.13361} $$

Therefore:

13.36%
	​


In [10]:
from scipy.stats import norm

prob_outlier = 2 * (1 - norm.cdf(1.5))

print(prob_outlier)
print(prob_outlier * 100)

0.13361440253771617
13.361440253771617


### Problem-10

The latency (delay) in a specific network segment is observed to be normally distributed with a mean of 150 ms and a standard deviation of 20 ms.

(a) What is the probability that a data packet experiences a latency greater than 180 ms?

(b) Due to new QoS (Quality of Service) requirements, 90% of packets must arrive within a certain latency threshold. What is this threshold (in ms)?

(c) If a network engineer defines "critical latency" as any latency exceeding 2.5 standard deviations above the mean, what is the probability that a packet experiences critical latency?

Network Latency

We are told that latency \(X\) is normally distributed with:

$$ \mu=150\text{ ms} $$ $$ \sigma=20\text{ ms} $$

The standard-score formula is:

\(z = \frac{x - \mu}{\sigma}\)
z=
1.8
(4)−(1.5)
	​

=1.389
Φ(z)≈91.8%
x
x
μ
μ
σ
σ
μ
x
Φ(z)
Give feedback
$$ z=\frac{x-\mu}{\sigma} $$
(a) Probability that latency is greater than 180 ms

We want:

$$ P(X>180) $$
Step 1: Calculate the z-score
$$ z=\frac{180-150}{20} $$ $$ z=\frac{30}{20}=1.5 $$

So:

$$ P(X>180)=P(Z>1.5) $$

From the standard normal table:

$$ P(Z<1.5)\approx0.9332 $$

Therefore:

$$ P(Z>1.5)=1-0.9332 $$ $$ =0.0668 $$
Answer
$$ \boxed{P(X>180)\approx0.0668} $$

or

$$ \boxed{6.68\%} $$

So approximately 6.68% of packets experience latency greater than 180 ms.

In [11]:
from scipy.stats import norm

mu = 150
sigma = 20

prob = 1 - norm.cdf(180, mu, sigma)

print(prob)
print(prob * 100)

0.06680720126885809
6.6807201268858085


Problem 10(b) — Latency threshold for 90% of packets

The requirement says:

90% of packets must arrive within the threshold.

Therefore, we need \(x\) such that:

$$ P(X\leq x)=0.90 $$

For the standard normal distribution, the z-score corresponding to the 90th percentile is approximately:

$$ z_{0.90}=1.2816 $$

We use:

$$ z=\frac{x-\mu}{\sigma} $$

Therefore:

$$ 1.2816=\frac{x-150}{20} $$

Multiply by 20:

$$ 25.632=x-150 $$

Therefore:

$$ x=175.632 $$
Answer
$$ \boxed{x\approx175.63\text{ ms}} $$

So the latency threshold should be approximately 175.6 ms for 90% of packets to arrive within the threshold.

In [12]:
from scipy.stats import norm

mu = 150
sigma = 20

threshold = norm.ppf(0.90, mu, sigma)

print(threshold)

175.631031310892


Problem 10(c) — Critical Latency

Critical latency is defined as more than 2.5 standard deviations above the mean.

Therefore:

$$ z>2.5 $$

We need:

$$ P(Z>2.5) $$

From the standard normal distribution:

$$ P(Z<2.5)\approx0.9938 $$

Therefore:

$$ P(Z>2.5)=1-0.9938 $$ $$ =0.0062 $$
Answer
$$ \boxed{P(\text{critical latency})\approx0.0062} $$

or:

0.62%
	​


In [13]:
from scipy.stats import norm

prob_critical = 1 - norm.cdf(2.5)

print(prob_critical)
print(prob_critical * 100)

0.006209665325776159
0.6209665325776159


### Problem-11

The lifespan of a certain electronic component, due to manufacturing variations, is normally distributed with a mean of 2500 hours and a standard deviation of 300 hours.

(a) A customer requires components that last at least 2000 hours. What percentage of manufactured components meet this requirement?

(b) The manufacturer wants to provide a warranty such that only 1% of components fail before the warranty period ends. What should be the warranty period (in hours)?

(c) If a batch of 10,000 components is produced, how many components are expected to have a lifespan between 2200 and 2800 hours?

Problem 11 — Component Lifespan

The lifespan \(X\) is normally distributed with:

$$ \mu=2500\text{ hours} $$ $$ \sigma=300\text{ hours} $$
(a) Percentage lasting at least 2000 hours

We want:

$$ P(X\geq2000) $$
Step 1: Calculate the z-score
$$ z=\frac{2000-2500}{300} $$ $$ z=\frac{-500}{300} $$ $$ z\approx-1.667 $$

Therefore:

$$ P(X\geq2000)=P(Z\geq-1.667) $$

Because the normal distribution is symmetric:

$$ P(Z\geq-1.667)=P(Z\leq1.667) $$

From the normal table:

$$ P(Z\leq1.667)\approx0.9522 $$
Answer
$$ \boxed{P(X\geq2000)\approx95.22\%} $$

So approximately 95.22% of manufactured components meet the customer's requirement.

In [14]:
from scipy.stats import norm

mu = 2500
sigma = 300

prob = 1 - norm.cdf(2000, mu, sigma)

print(prob)
print(prob * 100)

0.9522096477271853
95.22096477271853


Problem 11(b) — Warranty Period

The manufacturer wants only 1% of components to fail before the warranty period ends.

That means:

$$ P(X<w)=0.01 $$

We need the 1st percentile of the normal distribution.

The z-score corresponding to 0.01 is approximately:

$$ z=-2.3263 $$

Using:

$$ z=\frac{x-\mu}{\sigma} $$

we have:

$$ -2.3263=\frac{x-2500}{300} $$

Multiply by 300:

$$ -697.89=x-2500 $$

Therefore:

$$ x=2500-697.89 $$ $$ x\approx1802.11 $$
Answer
$$ \boxed{w\approx1802\text{ hours}} $$

So a warranty period of approximately 1,802 hours would correspond to about 1% of components failing before the warranty period ends, under the stated normal-distribution model.

In [15]:
from scipy.stats import norm

mu = 2500
sigma = 300

warranty_period = norm.ppf(0.01, mu, sigma)

print(warranty_period)

1802.0956377877478


Problem 11(c) — Components Between 2200 and 2800 Hours

We have:

$$ n=10,000 $$

We want:

$$ P(2200<X<2800) $$
Step 1: Calculate the z-score for 2200
$$ z_1=\frac{2200-2500}{300} $$ $$ z_1=-1 $$
Step 2: Calculate the z-score for 2800
$$ z_2=\frac{2800-2500}{300} $$ $$ z_2=1 $$

Therefore:

$$ P(2200<X<2800)=P(-1<Z<1) $$

For the standard normal distribution:

$$ P(-1<Z<1)\approx0.6827 $$

So approximately 68.27% of components fall in this range.

Step 3: Calculate the expected number
$$ 10,000\times0.6827 $$ $$ =6827 $$
Answer
Approximately 6,827 components
	​


In [16]:
from scipy.stats import norm

mu = 2500
sigma = 300
n = 10000

prob = norm.cdf(2800, mu, sigma) - norm.cdf(2200, mu, sigma)

expected_components = n * prob

print("Probability:", prob)
print("Expected components:", expected_components)

Probability: 0.6826894921370859
Expected components: 6826.894921370858


### Problem-12
The probability density function (pdf) of the triangular distribution is characterized by three points as shown in the figure below.

<img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Triangular_distribution_PMF.png" alt="triangular distribution" width="500"/>

(a) min value of the distribution,
(b) max value of the distribution, and
(c) mode of the distribution

Note: $a \leq c \leq b$

Create a class `TriangularDistribution` with attributes `min`, `max` and `mode`. You need to implement the following methods:

- `pdf(x)`: returns the value of the pdf at point $x$.
- `plot_pdf()`: plots the pdf in the range $[min , max]$
- `cdf(x)`: returns the value of the cdf at point $x$ ; which denotes $P(X \leq x)$
- `plot_cdf()`: plots the cdf in the range $[min , max]$
- `get_probability(x1, x2)`: returns the probability $P(x_1 \leq X \leq x_2)$, where $x_1 \lt x_2$.

Gracefully handle the possible errors and also the edge conditions when either $ a = c $ or $b = c$ in the distribution.

Test your implementation.

In [ ]:
### Write your code here


### Problem-13

The `rand5()` function which returns a uniform random integer within the range [1, 5], is defined as following:

```python
def rand5():
    import numpy as np
    return np.random.randint(1,6)
```

Write a function `rand7()` that will generate a uniform random integer within the range [1, 7] by only using `rand5()`. 

Note: You can call `rand5()` as many time as you want inside the function `rand7()`, but you can not use `np.random.randint(1, 8)` or any other built-in methods in python. 

We can solve this using rejection sampling. The key is to first generate a uniform number from 1–25 using two calls to rand5(), then reject values 22–25.

Step 1: Generate a number from 1 to 25

Each call to rand5() has 5 equally likely outcomes.

Let:
a=rand5()
b=rand5()
We can combine them as:

$$ ( a-1)\times5+b $$

This produces every integer from 1 to 25, each with probability \(1/25\).

For example:

\(a=1,b=1\) → 1
\(a=1,b=5\) → 5
\(a=2,b=1\) → 6
...
\(a=5,b=5\) → 25
Step 2: Keep only 1–21

Why 21?

Because:

$$ 21=7\times3 $$

So the numbers 1–21 can be divided evenly into 3 groups of 7:

1–7 → 1–7
8–14 → 1–7
15–21 → 1–7

Each number 1–7 will therefore occur exactly 3 times.

If we get 22–25, we simply discard it and try again.

In [21]:
def rand5():
    import numpy as np
    return np.random.randint(1, 6)


def rand7():
    while True:
        a = rand5()
        b = rand5()

        num = (a - 1) * 5 + b

        if num <= 21:
            return ((num - 1) % 7) + 1


Why is it uniform?

There are 25 equally likely combinations from two rand5() calls.

We accept only:

1,2,...,21

Each has probability:

1/25

Among those 21 values, each output from 1 to 7 appears exactly 3 times.

For example:

1,8,15\rightarrow 1 
2,9,16\rightarrow 2
...
7,14,21\rightarrow 7

Thus:

P(rand7=k)=3/21=1/7

for every k=1,..,7.

Therefore, rand7() generates a uniform integer from 1 to 7.
	​


### Problem-14

A grayscale image can be represented as a matrix where the dimensions are (height, width). 
Let's consider a simplified scenario with two grayscale images, $A$ and $B$, both represented as 10×10 matrices where each element represents pixel intensity. Pixel intensity is an integer in the range [0-255].

You want to create a blended image $C$ by combining $A$ and $B$ such that $C=w_1 A+w_2 B$. This represents a weighted average blend.
Note that each element in the resultant matrix $C$ should also fall within the range [0, 255]. 

write the code of the function `blend_images(image_A, image_B, weight_A, weight_B)` that takes two matrices and two scalar weights and produces another matrix as an output by performing the above operation.

Yes. Problem 14 is asking you to perform a weighted average of two image matrices.

The blending operation is:

$$ \boxed{\text{Blended Image}=weight_A\times image_A+weight_B\times image_B} $$

Typically, the weights should satisfy:

$$ weight_A+weight_B=1 $$

For example, if weight_A = 0.7 and weight_B = 0.3, the result is 70% image A and 30% image B.

Python solution using NumPy

In [22]:
import numpy as np

def blend_images(image_A, image_B, weight_A, weight_B):
    
    # Check that the weights add up to 1
    if not np.isclose(weight_A + weight_B, 1):
        raise ValueError("weight_A and weight_B must add up to 1")
    
    # Weighted average of the two images
    blended_image = weight_A * image_A + weight_B * image_B
    
    # Keep pixel values within the range [0, 255]
    blended_image = np.clip(blended_image, 0, 255)
    
    # Convert pixel intensities to integers
    blended_image = blended_image.astype(np.uint8)
    
    return blended_image


In [23]:
image_A = np.random.randint(0, 256, (10, 10))
image_B = np.random.randint(0, 256, (10, 10))

result = blend_images(image_A, image_B, 0.6, 0.4)

print(result)
print(result.shape)

[[200  35 146 128 214 122 145  50  74 127]
 [134 139  90 149  63 188 208  55  57 172]
 [211  84 133 192 140 181 222  73 197 199]
 [177 219 109 111 202 146 173 174 215  51]
 [ 91 141 149 104  57  46 172  41  79  73]
 [149 210 126 130  93 122 200 107 218  72]
 [ 99 160 186  85  99 192 141  39  98 218]
 [121 183 140  21 105 136 190 162 124  94]
 [ 61 193 182 191 157 228 169 205 110 110]
 [ 59  62 126  80 174 118  77 112 171 132]]
(10, 10)


In [24]:
import numpy as np

def blend_images(image_A, image_B, weight_A, weight_B):
    if not np.isclose(weight_A + weight_B, 1):
        raise ValueError("Weights must add up to 1")
    
    blended_image = weight_A * image_A + weight_B * image_B
    
    blended_image = np.clip(blended_image, 0, 255)
    
    return blended_image.astype(np.uint8)

### Problem-15

Calculate the eigen values and eigen vectors of the following matrices.

$A = \begin{bmatrix}
5 & 2 \\
2 & 2
\end{bmatrix}$      

$B = \begin{bmatrix}
1 & 1 & 0\\
0 & 2 & 0\\
-1 & 1 & 3
\end{bmatrix}$